### ISSUE TITLE
"not all keys accounted for" error upon loading

### ISSUE THREAD

**Issue by patriciaverso** [morinted/plover_portuguese#7]
**Steps to reproduce:**
* Have plover and plover-portuguese installed
* Start plover
* Select "Portuguese Stenotype" on Configure->System->System
* Apply
* A dialog should appear saying "ValueError: invalid `implicit_hyphen_keys`: not all keys accounted for"
* Typing any left side key yields an error like "ValueError: invalid keys mask: 0x800000000000000" with the value dependent on the key pressed
* Enable Plover Output
* Any key typed yields the error "ValueError: invalid steno: '-S'"

**Comment by j0hnd3v** [comment]
@patriciavillela 

> A dialog should appear saying "ValueError: invalid implicit_hyphen_keys: not all keys accounted for"
> Typing any left side key yields an error like "ValueError: invalid keys mask: 0x800000000000000" with the value dependent on

The last commit of this plugin is from 2018, if you install this plugin on a 2018 plover release this issue will not occur.

**Comment by patriciaverso** [comment]
@j0hnd3v Yes, of course. However, in the interest of fixing the issue instead of only downgrading the application one could ask for help around here. You know, open source?

Anyway, I'm here one year later trying to fix this once again. Any pointers would be helpful.

**Comment by patriciaverso** [comment]
For anyone dealing with this, this PR should solve it.
https://github.com/morinted/plover_portuguese/pull/6
